#### Required Python libraries

In [0]:
import numpy  as np
import matplotlib.pyplot as plt
import librosa  # package for speech and audio analysis
from sklearn import mixture
from sklearn.metrics import accuracy_score,confusion_matrix
from scipy.io import loadmat
from scipy.io import savemat
from torchvision import datasets, transforms
from sklearn.preprocessing import StandardScaler
import pylab as pl
import seaborn as sns
import pandas as pd
from sklearn.utils import shuffle
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.utils.fixes import loguniform
from sklearn.multiclass import OneVsRestClassifier
%config InlineBackend.figure_format = 'retina'   ##QUALITY FIGURES!!
import time
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier

from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV, StratifiedKFold


from sklearn.metrics import roc_auc_score, accuracy_score, precision_score, recall_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import mean_squared_error as mse
from sklearn.model_selection import cross_validate
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.svm import LinearSVC
from sklearn.ensemble import VotingClassifier
from sklearn.feature_selection import RFECV

In [0]:
import pandas as pd


In [0]:
XTrain = pd.read_csv('x_trainset_clean.csv', error_bad_lines=False)
XTest = pd.read_csv('x_testset_clean.csv', sep=";", error_bad_lines=False)
YTrain = pd.read_csv('y_trainset_clean.csv', error_bad_lines=False)


In [4]:
print(XTrain)
print(YTrain)
print(XTest)

print(XTrain.shape)
print(YTrain.shape)
print(XTest.shape)

        feat_0   feat_1   feat_2  ...  feat_144  feat_145  feat_146
0      15.1368  22.0563  13.8909  ...   10.5976    2.4412    7.8157
1      17.8086   6.7716   7.6309  ...   13.4864    5.5657   34.4324
2      16.6050   8.9661   5.2370  ...   14.1878    0.8427   14.5175
3      17.9498  21.0946  11.8534  ...   11.9454   -0.6505   32.5443
4      11.4204  23.7611   3.7186  ...   14.5033   10.0882   18.1030
...        ...      ...      ...  ...       ...       ...       ...
89411  20.9624  12.0519   5.5867  ...    7.8009    9.0138    5.8544
89412   1.6635  13.0759   3.8412  ...   10.5684   -3.0129   14.6587
89413  12.5236  24.9418  11.5404  ...   11.6344    5.8713   29.0477
89414   3.7362   2.2806   5.1252  ...    6.3111   -2.8103   11.0105
89415   6.0730  13.2655  10.4632  ...   10.6917    0.6781   27.1135

[89416 rows x 119 columns]
       target
0           0
1           0
2           0
3           0
4           0
...       ...
89411       1
89412       0
89413       0
89414       0
89

In [0]:
XTrain

feat_0   feat_1   feat_2  ...  feat_144  feat_145  feat_146
0      15.1368  22.0563  13.8909  ...   10.5976    2.4412    7.8157
1      17.8086   6.7716   7.6309  ...   13.4864    5.5657   34.4324
2      16.6050   8.9661   5.2370  ...   14.1878    0.8427   14.5175
3      17.9498  21.0946  11.8534  ...   11.9454   -0.6505   32.5443
4      11.4204  23.7611   3.7186  ...   14.5033   10.0882   18.1030
...        ...      ...      ...  ...       ...       ...       ...
89411  20.9624  12.0519   5.5867  ...    7.8009    9.0138    5.8544
89412   1.6635  13.0759   3.8412  ...   10.5684   -3.0129   14.6587
89413  12.5236  24.9418  11.5404  ...   11.6344    5.8713   29.0477
89414   3.7362   2.2806   5.1252  ...    6.3111   -2.8103   11.0105
89415   6.0730  13.2655  10.4632  ...   10.6917    0.6781   27.1135

[89416 rows x 119 columns]

In [5]:
!pip install imbalanced-learn
import imblearn
from imblearn.under_sampling import NearMiss
from collections import Counter

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


In [6]:
counter = Counter(YTrain)

print(counter)


Counter({'target': 1})


In [7]:
#undersample = NearMiss(version=3, n_neighbors_ver3=3)
#XTrain, YTrain = undersample.fit_resample(XTrain, YTrain)

from imblearn.under_sampling import RandomUnderSampler
from sklearn.model_selection import train_test_split

XTraining, XValidation, YTraining, YValidation = train_test_split(XTrain,YTrain, test_size=0.3) # before model building


rus = RandomUnderSampler(random_state=42)
XTraining, YTraining = rus.fit_resample(XTraining, YTraining)


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [8]:
print(XValidation.shape)
print(YValidation.shape)
print(XTraining.shape)
print(YTraining.shape)

(26825, 119)
(26825, 1)
(12566, 119)
(12566, 1)


In [9]:
scaler = StandardScaler()
XTraining = scaler.fit_transform(XTraining)
XValidation = scaler.transform(XValidation)
XTest = scaler.transform(XTest)
print(XTest.shape)



(44042, 119)


# Logistic Regression (LR)

In [10]:
#LOGISTIC REGRESSION:
from sklearn.metrics import f1_score

LR = LogisticRegression()

skf = StratifiedKFold(n_splits=20)

grid = {"C":[0.0001,0.001,0.01,0.1,1,10,100,1000,10000], 
        "penalty":["l2"]}

logreg_cv = GridSearchCV(LR, cv=skf, param_grid=grid, scoring = "f1")


logreg_cv.fit(XTraining, np.ravel(YTraining))

final_model_RF = logreg_cv.best_estimator_

print(logreg_cv.best_params_)

y_pred = final_model_RF.predict(XValidation)

f1_LR = f1_score(YValidation, y_pred, average=None)

print("F1:")
print(f1_LR)

results = final_model_RF.predict(XTest)

print(results.shape)
print(results)
dataset = pd.DataFrame({'ID': np.arange(0,44042), 'target': results})
print(dataset)
dataset.to_csv('LRpredictions.csv', index=False, sep=',')

{'C': 0.01, 'penalty': 'l2'}
F1:
[0.79596881 0.28993737]
(44042,)
[1 1 0 ... 0 0 0]
          ID  target
0          0       1
1          1       1
2          2       0
3          3       0
4          4       0
...      ...     ...
44037  44037       0
44038  44038       1
44039  44039       0
44040  44040       0
44041  44041       0

[44042 rows x 2 columns]


# Decision Tree (DT)

In [11]:
decision_tree = DecisionTreeClassifier()

#grid = {'max_leaf_nodes': list(range(2, 100)), 'min_samples_split': [ 2, 3, 4, 5, 6, 7 ]}

#DecTree_cv = GridSearchCV(decision_tree,grid,cv=5)


decision_tree.fit(XTraining, YTraining)


Y_pred_decision_tree = decision_tree.predict(XValidation)

decision_tree_f1 =  f1_score(YValidation, Y_pred_decision_tree, average= None)

print("F1:")
print(decision_tree_f1)

results = decision_tree.predict(XTest)

print(results.shape)
print(results)
dataset = pd.DataFrame({'ID': np.arange(0,44042), 'target': results})
print(dataset)
dataset.to_csv('DTpredictions.csv', index=False, sep=',')

F1:
[0.69927378 0.20175737]
(44042,)
[1 1 0 ... 0 0 0]
          ID  target
0          0       1
1          1       1
2          2       0
3          3       0
4          4       1
...      ...     ...
44037  44037       0
44038  44038       0
44039  44039       0
44040  44040       0
44041  44041       0

[44042 rows x 2 columns]


# Linear Discriminant Analysis (LDA)

In [12]:
LDA = LinearDiscriminantAnalysis()

LDA.fit(XTraining, YTraining)

Y_pred_LDA = LDA.predict(XValidation)

LDA_f1 =  f1_score(YValidation, Y_pred_LDA, average= None)


print("F1:")
print(LDA_f1)

results = LDA.predict(XTest)

print(results.shape)
print(results)
dataset = pd.DataFrame({'ID': np.arange(0,44042), 'target': results})
print(dataset)

dataset.to_csv('LDApredictions.csv', index=False, sep=',')

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


F1:
[0.7964415  0.28944505]
(44042,)
[1 1 0 ... 0 1 0]
          ID  target
0          0       1
1          1       1
2          2       0
3          3       0
4          4       0
...      ...     ...
44037  44037       0
44038  44038       1
44039  44039       0
44040  44040       1
44041  44041       0

[44042 rows x 2 columns]


# Quadratic Discriminant Analysis (QDA)

In [13]:
QDA = QuadraticDiscriminantAnalysis()

QDA.fit(XTraining, YTraining)

y_pred = QDA.predict(XValidation)

f1_QDA =  f1_score(YValidation, y_pred, average=None)


print("F1:")
print(f1_QDA)

results = QDA.predict(XTest)

print(results.shape)
print(results)
dataset = pd.DataFrame({'ID': np.arange(0,44042), 'target': results})
print(dataset)

dataset.to_csv('QDApredictions.csv', index=False, sep=',')

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


F1:
[0.7409184  0.23884322]
(44042,)
[0 1 1 ... 0 0 0]
          ID  target
0          0       0
1          1       1
2          2       1
3          3       1
4          4       0
...      ...     ...
44037  44037       1
44038  44038       0
44039  44039       0
44040  44040       0
44041  44041       0

[44042 rows x 2 columns]


# Random Forest (RF)

In [14]:
random_forest = RandomForestClassifier()

param_grid = { 
    'n_estimators': [100, 200, 300],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth' : [4,5,6],
    'criterion' :['gini', 'entropy']
}
Grid_RandomForest = GridSearchCV( estimator = random_forest, param_grid=param_grid, cv= 5)


random_forest.fit(XTraining, YTraining)


y_pred = random_forest.predict(XValidation)

f1_random_forest =  f1_score(YValidation, y_pred, average=None)


print("F1:")
print(f1_random_forest)

results = random_forest.predict(XTest)

print(results.shape)
print(results)
dataset = pd.DataFrame({'ID': np.arange(0,44042), 'target': results})
print(dataset)

dataset.to_csv('RFpredictions.csv', index=False, sep=',')

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  if sys.path[0] == '':


F1:
[0.78683931 0.2799086 ]
(44042,)
[0 0 0 ... 1 1 0]
          ID  target
0          0       0
1          1       0
2          2       0
3          3       1
4          4       0
...      ...     ...
44037  44037       0
44038  44038       0
44039  44039       1
44040  44040       1
44041  44041       0

[44042 rows x 2 columns]


# KNN

In [15]:
KNN = KNeighborsClassifier()


#parameters = {'n_neighbors':[3,4,5,6,7,10],
 #              'weights' : ['uniform','distance']
  #            'leaf_size':[1,3,5],
   #           'algorithm':['auto', 'kd_tree']}


#Grid_KNN = GridSearchCV( estimator = KNN, param_grid=parameters, cv= 5)


KNN.fit(XTraining, YTraining)

y_pred = KNN.predict(XValidation)

f1_score_KNN =  f1_score(YValidation, y_pred, average=None)

print("F1:")
print(f1_score_KNN)

results = KNN.predict(XTest)

print(results.shape)
print(results)
dataset = pd.DataFrame({'ID': np.arange(0,44042), 'target': results})
print(dataset)

dataset.to_csv('KNNpredictions.csv', index=False, sep=',')

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  del sys.path[0]


F1:
[0.81115079 0.19990239]
(44042,)
[0 0 1 ... 0 0 0]
          ID  target
0          0       0
1          1       0
2          2       1
3          3       1
4          4       0
...      ...     ...
44037  44037       0
44038  44038       0
44039  44039       0
44040  44040       0
44041  44041       0

[44042 rows x 2 columns]


# Gaussian NB

In [20]:
from sklearn.metrics import f1_score
from sklearn.model_selection import cross_val_score

bayes = GaussianNB()

skf = StratifiedKFold(n_splits=20)

bayes = GridSearchCV(bayes, cv=skf, param_grid={}, scoring = "f1")

bayes.fit(XTraining, np.ravel(YTraining))

y_pred_NB = bayes.predict(XValidation)

f1_NB = f1_score(YValidation, y_pred_NB, average=None)

print("F1:")
print(f1_NB)

results = bayes.predict(XTest)
print(results)
print(results.shape)
dataset = pd.DataFrame({'ID': np.arange(0,44042), 'target': results.astype(int)})
print(dataset)
dataset.to_csv('GNBpredictions.csv', index=False, sep=',')



F1:
[0.81090193 0.30913349]
[1 1 0 ... 0 0 0]
(44042,)
          ID  target
0          0       1
1          1       1
2          2       0
3          3       0
4          4       0
...      ...     ...
44037  44037       0
44038  44038       0
44039  44039       0
44040  44040       0
44041  44041       0

[44042 rows x 2 columns]


# XGB Classifier

In [21]:
# Create Learners per layer
from sklearn.ensemble import StackingClassifier
from xgboost import XGBClassifier

layer_one_estimators = [
                        ('random_forest', RandomForestClassifier()),
                        ('LDA', LinearDiscriminantAnalysis()),
                        ('bayes', GaussianNB())
                        
                        
                       ]
layer_two_estimators = [
                        ('xgb', XGBClassifier( n_estimators=600, objective='binary:logistic', silent=True, nthread=1,
                                    subsample = 0.8, min_child_weight = 10,  max_depth = 5, learning_rate = 0.02,
                                    gamma = 1, colsample_bytree =1
                        ))
                       ]



layer_two = StackingClassifier(estimators=layer_two_estimators, final_estimator=LogisticRegression(C=0.1))

# Create Final model by 
grid_final = StackingClassifier(estimators=layer_one_estimators, final_estimator=layer_two)


grid_final.fit(XTraining, np.ravel(YTraining))

y_pred_mix = grid_final.predict(XValidation)

f1_mix = f1_score(YValidation, y_pred_mix, average=None)

print("F1:")
print(f1_mix)

F1:
[0.8259408 0.3105234]


# Stacking classifiers

In [0]:
layer_one_estimators = [
                          ('LDA', LinearDiscriminantAnalysis()),
                          ('random_forest', RandomForestClassifier(random_state = 51)),
                          ('bayes', GaussianNB())
                       ]

layer_two_estimators = [
                        ('xgb', XGBClassifier( n_estimators=600, objective='binary:logistic', silent=True, nthread=1,
                                    subsample = 0.8, min_child_weight = 10,  max_depth = 5, learning_rate = 0.02,
                                    gamma = 1, colsample_bytree =1, random_state = 51
                        ))
                       ]


layer_two = StackingClassifier(estimators=layer_two_estimators, final_estimator=LogisticRegression())

# Create Final model by 
grid_final = StackingClassifier(estimators=layer_one_estimators, final_estimator=layer_two)


grid_final.fit(XTraining, np.ravel(YTraining))

y_pred_mix = grid_final.predict(XValidation)

f1_mix = f1_score(YValidation, y_pred_mix, average=None)

print("F1:")
print(f1_mix)

F1:
[0.79837971 0.31323916]
